name: Create a GitHub release
description: 'GHA to create a GitHub release'

branding:
  icon: archive
  color: green

runs:
  using: "composite"
  steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout profile
        uses: actions/checkout@v4
        if: ${{ hashFiles('.github/release.yml') != '' }}
        with:
          repository: "${{ github.repository_owner }}/.github"
          sparse-checkout: .github/release.yml
          sparse-checkout-cone-mode: false

      - name: Create Release Page
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} --generate-notes
